# Generated by Django 4.1 on 2023-02-21 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome do ativo')),
                ('description', models.CharField(max_length=100, verbose_name='Descrição')),
                ('market', models.CharField(max_length=50, verbose_name='Mercado')),
                ('currency', models.CharField(max_length=10, verbose_name='Moeda')),
                ('type', models.CharField(max_length=50, verbose_name='Tipo de investimento')),
                ('group', models.CharField(max_length=50, verbose_name='Grupo de investimento')),
                ('expiration_date', models.DateTimeField(verbose_name='Vencimento')),
            ],
        ),
    ]
