# Generated by Django 4.1 on 2023-02-22 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0002_wallet_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={'verbose_name': 'Ativo'},
        ),
        migrations.AlterModelOptions(
            name='wallet',
            options={'verbose_name': 'Carteira'},
        ),
        migrations.AlterField(
            model_name='asset',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Vencimento'),
        ),
    ]
